
+++
date = "2017-08-18 23:46:15 +0000 UTC"
draft = false
title = "gRPC ServerのExceptionFilterの方法をまとめた（grpc-java）"
tags = ["gRPC","Exception","Filter","Interceptor"]

+++
前回のエントリでは認証処理やメトリクス計測、ログ出力などをインターセプターをつかい横断的に処理する方法をまとめた。

[Kotlin + gRPCでio.grpc.Contextをつかってログ出力を横断処理してみた - 平日インプット週末アウトプットぶろぐ](http://naruto-io.hatenablog.com/entry/2017/07/20/101051)

今回のエントリではgRPC Serverのトランザクション内で発生した例外処理を横断的にキャッチしてレスポンスを返す方法をまとめていきたい。

### try-catchして例外クラスに応じた処理を施す

愚直に書けば次のようになるだろう。

```kotlin
override fun getTaskService(request: TaskInbound?, responseObserver: StreamObserver&lt;TaskOutbound>?) {
    try {
        val taskId = GRpcInboundValidator.validTaskInbound(request)

        val log = GRpcLogContextHandler.getLog()
        log.elem { "taskId" to taskId }

        val task = getTaskService(GetTaskCommand(taskId.toLong()))
        val msg = getOutbound(task)
        responseObserver?.onNext(msg)
        responseObserver?.onCompleted()
    } catch (e: WebAppException.NotFoundException) {
        logger.error { "gRPC server error, task not found." }
        responseObserver?.onError(
                Status.NOT_FOUND.withDescription("task not found.").asRuntimeException())
    } catch (e: WebAppException.BadRequestException) {
        logger.error { "gRPC server error, invalid request." }
        responseObserver?.onError(
                Status.INVALID_ARGUMENT.withDescription("invalid request.").asRuntimeException())
    }
}

```


タスクを１件取得するgRPC Serverのコード例である。<br/>
タスクがなかった場合には<code>NOT FOUND</code>のレスポンス、リクエストに不備があれば<code>INVALID_ARGUMENT</code>のレスポンスを返していることがわかる。<br/>
レスポンスを返す直前にはExceptionをキャッチしている。そしてExceptionごとにエラーレスポンスを並べている形だ。

このような書き方を複数のgRPC Serverで続けると<code>catch</code>節が冗長になってしまう。<br/>
gRPC ServerのインターセプターをつかいExceptionのキャッチを共通処理としていきたい。そうすれば上記のコードからtry-catchが無くなりコードの見通しが良くなる。

### インターセプターをつくる

gRPC Serverのトランザクションで発生した例外をキャッチするには次のようなインターセプターを用意する。

```kotlin
@Component
class ExceptionFilter : ServerInterceptor {

    private val logger = KotlinLogging.logger {}

    override fun &lt;ReqT : Any?, RespT : Any?> interceptCall(call: ServerCall&lt;ReqT, RespT>?, headers: Metadata?,
                                                           next: ServerCallHandler&lt;ReqT, RespT>?): ServerCall.Listener&lt;ReqT> {
        return object : ForwardingServerCallListener.SimpleForwardingServerCallListener&lt;ReqT>(next?.startCall(call, headers)!!) {

            override fun onHalfClose() {
                try {
                    super.onHalfClose()
                } catch (ex: RuntimeException) {
                    handleException(call, headers, ex)
                    throw ex
                }
            }

            override fun onReady() {
                try {
                    super.onReady()
                } catch (ex: RuntimeException) {
                    handleException(call, headers, ex)
                    throw ex
                }

            }
        }
    }

```


<ul>
<li><code>onHalfClose</code>と<code>onReady</code>をoverrideしたリスナーを用意する。<code>onHalfClose</code>と<code>onReady</code>はクライアントからリクエストが送信された後、つまりServer内の処理のリスナーである。</li>
<li>この２つリスナー関数をtry-catchで囲むことでgRPC Server内の例外エラーを横断的にキャッチすることができる。</li>
</ul>


```kotlin
private fun &lt;ReqT, RespT> handleException(call: ServerCall&lt;ReqT, RespT>?, headers: Metadata?, ex: Exception) {

    logger.error(ex) { ex.message }

    when (ex) {
        is RepositoryException.NotFoundException -> call?.close(
                Status.fromCode(Status.NOT_FOUND.code).withDescription(ex.message), headers)
        is RepositoryException.ConflictException -> call?.close(
                Status.fromCode(Status.ALREADY_EXISTS.code).withDescription(ex.message), headers)
        is WebAppException.BadRequestException -> call?.close(
                Status.fromCode(Status.INVALID_ARGUMENT.code).withDescription(ex.message), headers)
        is WebAppException.NotFoundException -> call?.close(
                Status.fromCode(Status.NOT_FOUND.code).withDescription(ex.message), headers)
        is EmptyResultDataAccessException -> call?.close(
                Status.fromCode(Status.NOT_FOUND.code).withDescription("data not found."), headers)
        else -> call?.close(Status.fromCode(Status.INTERNAL.code).withDescription(ex.message), headers)
    }
}

```


<ul>
<li><code>handleException</code>関数では例外クラスに応じたれステータスコードを定義して<code>call?.close</code>を呼び出している。</li>
<li>これでExceptionFilterが例外エラーをすべてキャッチしてレスポンスを返すことができる。</li>
</ul>


### gRPC Serverのテスト時にExceptionFilterをつかう

gRPC ServerでExceptionFilterクラスをテストしたい。その場合にはテスト時に<code>InProcessServer</code>のビルダーに<code>intercept</code>を加えるとよい。

```kotlin
inProcessServer = InProcessServerBuilder
        .forName(UNIQUE_SERVER_NAME)
        .addService(target)
        .intercept(ExceptionFilter())  ← こちら
        .directExecutor()
        .build()

```


### まとめ

<ul>
<li>今回の例外エラーのキャッチ方法は情報が少なくgrpc-javaのissueのコメントで少し言及されていたところからヒントを得た。</li>
<li>振り返ると<code>ServerCallListener</code>のドキュメントを読んだうえで、それぞれのリスナーの役割を理解できれば実装できるものだった。</li>
<li>gRPCの実用化に向けてインターセプターのネタも揃ってきた。</li>
</ul>


### コード

エントリで紹介したコードは一部分のためコード全体はgithubを参照してください。


<div class="github-card" data-user="nsoushi" data-repo="spring5-kotlin-application" data-width="400" data-height="" data-theme="default"></div>
<script src="https://cdn.jsdelivr.net/github-cards/latest/widget.js"></script>


インターセプターのコードは<a href="https://github.com/nsoushi/spring5-kotlin-application/blob/master/backend/src/main/kotlin/app/grpc/interceptor/ExceptionFilter.kt">こちら</a>です。


